### ISSUE TITLE
config.json not found

### ISSUE THREAD

**Issue by ifoam** [fkasler/phishmonger#1]
I'm getting this error. config.json isn't part of this package or flik. I do see config.json is part of gitignore. 

How should I resolve this?

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open './config.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/home/tachc/phishmonger/index.js:286:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by therealelyayo** [comment]
root@vps-zap798175-1:~/phishmonger# node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'bunyan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/phishmonger/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
root@vps-zap798175-1:~/phishmonger# cd setup
root@vps-zap798175-1:~/phishmonger/setup# ls
domain_setup.sh  gandi_setup.js  kali_setup.sh
root@vps-zap798175-1:~/phishmonger/setup#



kindly note  you should include the  dependencies so as  to make installation abrezze  i can  help  you  write a  script to install  dependencies before we run node index.js 


i await your reply

**Comment by fkasler** [comment]
I'll look back at the playbook, but should be done by Flik:

https://github.com/fkasler/flik/blob/main/templates/pm_config.json

**Comment by fkasler** [comment]
@therealelyayo your issue seems to be something entirely different. If you set up with Flik, it will run 'npm install' for you and you will not have that problem. If you have other issues, please do not piggy-back on other open issues.

**Comment by fkasler** [comment]
@ifoam, can you give me some more context on how you are running Flik? The playbook for PM setup has a step in it for copying over a config.json.

**Comment by DarkReitor** [comment]
node index.js is asking for the config file

**Comment by fkasler** [comment]
@DarkReitor config.json will have settings like the authentication cookie to access the admin portal. It is intentionally left out of the project. If you set up with Flik, as per the README and noted above, it will create the correct config for you. Did you try setting up with Flik?

**Comment by DarkReitor** [comment]
> @DarkReitor config.json will have settings like the authentication cookie to access the admin portal. It is intentionally left out of the project. If you set up with Flik, as per the README and noted above, it will create the correct config for you. Did you try setting up with Flik?

No I haven't but the other repo you mention it needs an account. does that charge any amount to the account when I deploy it?

**Comment by fkasler** [comment]
Flik is just meant to work well with Gandi's API to set the right DNS records and get a wildcard LetsEncrypt cert. You can just set the DNS records manually and get the cert yourself but might need to look at the code to understand which ones to set. I'm looking into using Caddy to automate this setup for more registrars but that will take some significant refactoring. Your bet for now would just be to check out https://github.com/fkasler/flik/blob/main/templates/pm_config.json as a reference and fill out the options.
