### ISSUE TITLE
Strange Error in all browsers but Safari

### ISSUE THREAD

**Issue by ontinternet** [fkasler/phishmonger#5]
Hi,
When I have set up a test (or campaign) - everything works as it should through Safari. However, if the phishing link is clicked in a different browser, I am not being redirected to the target via the MitM of my phishing url.

The strange thing is that it appears to be trying to re-direct to the fake (target1) url, but this also is erroring.

Any ideas why:
1. The phishing url is not working in any browser other than Safari.
2. Why the error is happening for urls that should get redirected to the fake (target1) url.

The error I see when the redirect fails is below:
`<IP Redacted>:GET:https://<fake target1 url>/
problem with:https://<Fake target1 url>/
(node:1157) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rawBody' of undefined
    at humble_proxy (/root/tools/humble_chameleon/index.js:249:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
<ip Redacted>:GET:https:/fake target1 url/favicon.ico
problem with:https://fake target1 url/favicon.ico
(node:1157) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rawBody' of undefined
    at humble_proxy (/root/tools/humble_chameleon/index.js:249:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1157) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)`

Any help on this would be much appreciated.

**Comment by ontinternet** [comment]
**Update**
It seems Safari is the same as well (was cached from when working), so it looks like I have broken something...
